version: 2
jobs:
  build:

    working_directory: ~/spring-boot-feign-demo

    docker:
      - image: circleci/openjdk:11-jdk-stretch

    steps:
      - checkout
      - restore_cache:
          key: spring-boot-feign-demo-{{ checksum "pom.xml" }}

      - run: mvn clean install
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-spring-boot-feign-demo-{{ checksum "pom.xml" }}

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/spring-boot-feign-demo-0.0.1-SNAPSHOT.jar